#  ________  ___  ___  ________   ___  ________  ___  ___  _____ ______   ________  ________  _________  _______   ________
#|\   __  \|\  \|\  \|\   ___  \|\  \|\   ____\|\  \|\  \|\   _ \  _   \|\   __  \|\   ____\|\___   ___\\  ___ \ |\   __  \
#\ \  \|\  \ \  \\\  \ \  \\ \  \ \  \ \  \___|\ \  \\\  \ \  \\\__\ \  \ \  \|\  \ \  \___|\|___ \  \_\ \   __/|\ \  \|\  \
# \ \   ____\ \  \\\  \ \  \\ \  \ \  \ \_____  \ \   __  \ \  \\|__| \  \ \   __  \ \_____  \   \ \  \ \ \  \_|/_\ \   _  _\
#  \ \  \___|\ \  \\\  \ \  \\ \  \ \  \|____|\  \ \  \ \  \ \  \    \ \  \ \  \ \  \|____|\  \   \ \  \ \ \  \_|\ \ \  \\  \|
#   \ \__\    \ \_______\ \__\\ \__\ \__\____\_\  \ \__\ \__\ \__\    \ \__\ \__\ \__\____\_\  \   \ \__\ \ \_______\ \__\\ _\
#    \|__|     \|_______|\|__| \|__|\|__|\_________\|__|\|__|\|__|     \|__|\|__|\|__|\_________\   \|__|  \|_______|\|__|\|__|
#                                       \|_________|                                 \|_________|

##################################################################################################################
# Warning. Changing the configuration without knowledge can lead to problems.                                    #
# I've done my best to make the plugin configuration as simple as possible.                                      #
# But, if you need help configuring your plugin, you can join my Development Discord: https://discord.makzou.be/ #
##################################################################################################################

main:
  lang: "en_US" # Supported languages can be find in "./plugins/PunishMaster/lang/".
  check_update: true # Enables the plugin to run a check (at startup) to see if a newer version is available.
  enable_bstats: true # Enables the plugin to activate "bstats", allowing it to receive statistics (connected players / number of servers using the plugin). These two values and ONLY these two values. Can also be disabled from "bstats" configuration.

  #############################################################################################################
  # Note: This function is completely USELESS in the case of unauthorized access to the plugin name.          #
  # Since the plugin is OpenSource, it's easy to recover the encryption algorithm behind this protection.     #
  # Stay vigilant. They may not have access to your encryption code, but if they do, the data will be theirs. #
  # Recommended anyway.                                                                                       #
  #############################################################################################################
  cryptography_key: "replaceme" # To protect your database of players IP addresses from unauthorized access. You MUST replace this text with a text of your choice, anything like: "chat123", "ilovefrenchbaguette123", "illeatpizzatomorrowyeah".
system:
  proxy:
    # Need to be enabled if you've a Proxy (BungeeCord, Velocity, Waterfall, etc...) behind your gameserver.
    proxy_mode: false

    # Need to be enabled if you've some Proxies (using RedisBungee) behind your gameserver.
    # Unused at this moment.
    redisbungee_mode: false
database:
  # SQLite Punishment saver. In a file based database.
  # Not compatible with RedisBungee or Proxied mode.
  sqlite:
    use: true # Default : true
    hostname: ""
    username: ""
    password: ""
    database_name: ""
  # MySQL Punishment saver. In a database.
  mysql:
    use: false # Default: false
    hostname: "replace me if necessary"
    username: "replace me if necessary"
    password: "replace me if necessary"
    database_name: "replace me if necessary"
    port: "3306"
permissions:
  commands:
    help: "punishmaster.command.help"
    ban: "punishmaster.command.ban"
    unban: "punishmaster.command.unban"
    ban_ip: "punishmaster.command.ban-ip"
    unban_ip: "punishmaster.command.unban-ip"
    mute: "punishmaster.command.mute"
    unmute: "punishmaster.command.unmute"
    mute_ip: "punishmaster.command.mute-ip"
    unmute_ip: "punishmaster.command.unmute-ip"
    kick: "punishmaster.command.kick"
    kick_ip: "punishmaster.command.kick-ip"
    history: "punishmaster.command.history"
    staff_history: "punishmaster.command.staff-history"
    rollback: "punishmaster.command.rollback"
    lockdown: "punishmaster.command.lockdown"
    staff_chat: "punishmaster.command.staff-chat"
  chat:
    staffchat_view: "punishmaster.chat.staffchat"
    view_punishment: "punishmaster.chat.view-punishment"


