main:
  prefix: "§6[§cPunishMaster§6]"
  lang: "en_US"
system:
  proxy:
    # Need to be enabled if you've a Proxy behind your gameserver.
    use_bungeecord: false
    # Need to be enabled if you've some Proxy (using RedisBungee) behind your gameserver.
    # Unused at this moment. use_bungeecord need to be enabled too.
    use_redisbungee: false
database:
  # JSON Punishment saver. In a file.
  json:
    use: true
    file_name: "punishments.json"
  # MySQL Punishment saver. In a database.
  mysql:
    use: false
    hostname: ""
    username: ""
    password: ""
    database_name: ""
    port: "3306"
  # Recommanded. MongoDB Punishment saver. In a database.
  mongodb:
    use: false
    hostname: ""
    username: ""
    password: ""
    database_name: ""
    port: "27017"
  # SQLite Punishment saver. In a file based database.
  sqlite:
    use: false
    hostname: ""
    username: ""
    password: ""
    database_name: ""
permissions:
  commands:
    help: "punishmaster.command.help"
    ban: "punishmaster.command.ban"
    unban: "punishmaster.command.unban"
    ban-ip: "punishmaster.command.ban-ip"
    unban-ip: "punishmaster.command.unban-ip"
    mute: "punishmaster.command.mute"
    unmute: "punishmaster.command.unmute"
    mute-ip: "punishmaster.command.mute-ip"
    unmute-ip: "punishmaster.command.unmute-ip"
    kick: "punishmaster.command.kick"
    history: "punishmaster.command.history"
    staff-history: "punishmaster.command.staff-history"
    rollback: "punishmaster.command.rollback"
    lockdown: "punishmaster.command.lockdown"
    staff-chat: "punishmaster.command.staff-chat"
  chat:
    staffchat-view: "punishmaster.chat.staffchat"
    view-punishment: "punishmaster.chat.view-punishment"


